# This is a basic workflow to help you get started with Actions
name: fenbi-cuoti-daily-review

# Controls when the workflow will run
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bot:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib numpy requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Update star questions
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: python fenbi.py
